name: arXiv Daily

on:
  schedule:
    - cron: '0 1 * * *'   # 每天UTC时间1点自动运行
  workflow_dispatch:

jobs:
  run-arxiv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main   # 如果你的主分支不是 main，请改为你的主分支名

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt stopwords

      - name: Update score files
        run: |
          python arxiv_rank.py update

      - name: Generate daily HTML
        run: |
          python arxiv_rank.py

      - name: Copy and move HTML files
        run: |
          today=$(date +%Y%m%d)
          cp $today.html index.html
          mv $today.html arxiv_history/

      - name: Commit and push changes to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add favorite_arxiv_links.txt author.pickle title_abstract.pickle index.html arxiv_history/
          git commit -m "Auto update arxiv daily results [skip ci]" || echo "Nothing to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true